local applyItemDetails = require "gameNight - applyItemDetails"

local tarotCards = {
	"Ace of Wands",
	"Two of Wands",
	"Three of Wands",
	"Four of Wands",
	"Five of Wands",
	"Six of Wands",
	"Seven of Wands",
	"Eight of Wands",
	"Nine of Wands",
	"Ten of Wands",
	"Princess of Wands",
	"Knight of Wands",
	"Queen of Wands",
	"King of Wands",
	"Ace of Cups",
	"Two of Cups",
	"Three of Cups",
	"Four of Cups",
	"Five of Cups",
	"Six of Cups",
	"Seven of Cups",
	"Eight of Cups",
	"Nine of Cups",
	"Ten of Cups",
	"Princess of Cups",
	"Knight of Cups",
	"Queen of Cups",
	"King of Cups",
	"Ace of Swords",
	"Two of Swords",
	"Three of Swords",
	"Four of Swords",
	"Five of Swords",
	"Six of Swords",
	"Seven of Swords",
	"Eight of Swords",
	"Nine of Swords",
	"Ten of Swords",
	"Princess of Swords",
	"Knight of Swords",
	"Queen of Swords",
	"King of Swords",
	"Ace of Pentacles",
	"Two of Pentacles",
	"Three of Pentacles",
	"Four of Pentacles",
	"Five of Pentacles",
	"Six of Pentacles",
	"Seven of Pentacles",
	"Eight of Pentacles",
	"Nine of Pentacles",
	"Ten of Pentacles",
	"Princess of Pentacles",
	"Knight of Pentacles",
	"Queen of Pentacles",
	"King of Pentacles",
	"The Foolish Man",
	"The Magician",
	"The High Priestess",
	"The Empress",
	"The Emperor",
	"The Hierophant",
	"The Lovers",
	"The Chariot",
	"Fortitude",
	"The Hermit",
	"Wheel of Fortune",
	"Justice",
	"The Hanged Man",
	"Death",
	"Temperance",
	"The Devil",
	"The Blasted Tower",
	"The Star",
	"The Moon",
	"The Sun",
	"The Last Judgment",
	"Universe",
}

applyItemDetails.addDeck("TarotCards2", tarotCards)
